name: rootstock-mcp
displayName: Rootstock Blockchain MCP Server
description: Model Context Protocol server for Rootstock blockchain (testnet) interactions
version: 1.0.0
author: Rootstock MCP Team
license: MIT

# Force Node.js runtime (no Docker) - same as working Hyperion
runtime:
  type: nodejs
  version: "22"

# Build configuration
build:
  type: npm
  command: npm run build
  outputDir: build

# Start configuration
start:
  type: nodejs
  command: node build/smithery-server.js

# Entry point
entry: src/smithery-server.ts

# Dependencies
install:
  command: npm install

# Environment
environment:
  NODE_ENV: production
  ROOTSTOCK_RPC_URL: https://public-node.testnet.rsk.co
  ROOTSTOCK_CHAIN_ID: 31
  ROOTSTOCK_API_TIMEOUT: 60000
  ROOTSTOCK_MAX_RETRIES: 5

# Disable Docker - same as working Hyperion
docker:
  enabled: false
  
# Categories and metadata
categories:
  - blockchain
  - cryptocurrency
  - wallet
  - defi
  - tokens
  - erc20

keywords:
  - rootstock
  - rootstock-testnet
  - blockchain
  - cryptocurrency
  - wallet
  - trbtc
  - smart-contracts
  - defi
  - mcp
  - model-context-protocol
  - chain-31
  - erc20
  - token
  - token-deployment
  - token-minting
